### ISSUE TITLE
Species not included as public information in metadata

### ISSUE THREAD

**Issue by StuMackenzie** [MotusWTS/Motus-TO-DO#14]

**Comment by Hussell** [comment]
I'm assuming you mean, for example, here and here:
https://motus.org/data/downloads Tag deployments
https://motus.org/data/projectTags?id=20

The species is visible for a few tag deployments, but currently the majority of tag deployments (~58%) are not visible to the public because any deployment with a status of "pending" is invisible. A quick fix would be to just make pending deployments visible, but the correct, long-term fix is to calculate status from the current date and deployment date, so that deployments which really are pending will still be hidden.
