### ISSUE TITLE
New antenna options

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#21]
1) Can we add more options to the antenna drop-down menu:

9 element Yagi Laird PLC-1669
9 element Yagi Maple Leaf 9E166
6 element (custom)
9 element (custom)

2) Add the model number to all current 9-element antenna's in the system (9 element Yagi Laird PLC-1669)

**Comment by Hussell** [comment]
Changing all four thousand plus 9-element yagis to Laird PLC-1669s is probably incorrect. The generic "9-element Yagi" should be kept for antennas whose model is unknown (to us).

"yagi-9-liard" should be "yagi-9-laird".

Antennas with specific model numbers should probably just use the model number for the description, e.g. "Laird PLC1669" instead of "9-element Yagi Laird PLC-1669".

My guess for French for "6-element, custom" is "6 éléments, personnalisée", similarly for 9.

Up until now we've only been recording the generic type of the antenna. Did I miss a discussion about this? If we do want to record the model of each antenna, it might be better to add an optional free-form text field instead of mixing type and model # in the same field.

**Comment by Hussell** [comment]
Note that this field is being used by the receiver location map to determine antenna detection lobe shapes and sizes. When 'yagi-9' was changed, the map reverted to showing a default shape for 4000+ antennas.

https://motus.org/data/receiversMap.jsp

**Comment by cjardine-bsc** [comment]
I added a generic yagi-9 to the lookup table and set only the antennas from projects 1 and 2 to yagi-9-laird. 

Jeremy has updated the map to accept all three yagi-9 antenna_type field values (yagi-9, yagi-9-laird, yagi-9-
