### ISSUE TITLE
Tag ID and project ID can be inconsistent

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#26]
E.g. if I edit a tag:
https://sandbox.motus.org/data/tags/edit?projectID=72&id=14377

But change the project ID to another project on which I have permission to edit tags:
https://sandbox.motus.org/data/tags/edit?projectID=3&id=14377

Then I don't receive any warnings or errors, and the page makes it look as though the tag belongs to the wrong project. This is very confusing when it's noticed at all, and makes it difficult to detect bugs in generated links (because it often isn't noticed).

**Comment by pmorrill** [comment]
I am adding a validation filter for this. If the validation fails, my intention is to send the user to the correct PROJECT page above the tool they are viewing, rather than to the correct RESOURCE page.

Hitting this:
https://sandbox.motus.org/data/tags/edit?projectID=3&id=14377

will take the user to:
https://sandbox.motus.org/data/project/tags?projectID=3

Comment now if this is not the behaviour that you want.

**Comment by Hussell** [comment]
If the project of the resource and the project ID conflict, then something has gone wrong, so you should probably just send them straight back to the data management page with no project selected and an error message.
https://sandbox.motus.org/data/
