### ISSUE TITLE
Browse projects: what should be in the table?

### ISSUE THREAD

**Issue by Hussell** [MotusWTS/Motus-TO-DO#57]
From Zoe:

I got an email from a user with a suggestion for what's searchable on the projects page: https://motus.org/data/projects

They were searching for what project a certain tag was from, the shortlabel that they get with their hourly summary plot was "Niles" (from the fullID of Niles#325:19.9 M.24700), so they searched for that, but the project is really "47. Red Knot Staging and migration ecology" so nothing came up.  In the end she googled it and somehow it came up.  If we have access to John's shortlabels, can that be added as a search parameter?  I think now it only searches the project titles.

In the new data format there's a column for project #, so it should be easier to find and this issue can maybe be ignored, but there is still a field for fullID which includes the short label.  Also, if John continues with the hourly summary plots once the data is re-run (not sure of the plan for that), then it may still be worth to include a searcheable short label.

**Comment by Hussell** [comment]
Note that everything which is visible in the table is searched. I think that it would be very confusing to have a hidden field which is searched, so the question becomes: should the short project name, currently used by John, be added to the table?

**Comment by jbrzusto** [comment]
Yes!  The short project name is also in the R-compatible databases
people receive, as part of the full tag ID. It's important to have a
short human-readable handle for each project, and these have been in
datasets from sensorgnome.org since the beginning.  Whenever someone
references a tag, unless they give the integer motusID, they will
likely be giving a fullID like 'Niles#123:5.6' where the part before
'#' is the short project name.

**Comment by Hussell** [comment]
I've added the short name to the projects table. https://beta.motus.org/data/projects
